#!/usr/bin/env bash
# Generates STATUS.md from YAML frontmatter across all .md files.
# Run from repo root: ./scripts/status.sh
#
# Requires bash 4+ (brew install bash on macOS).
#
# Filtering: parse_frontmatter() skips any file missing type or status in its
# YAML frontmatter, so top-level docs (README, CLAUDE.md, etc.) are excluded
# automatically. The find command only needs to exclude templates and dirs that
# should never be scanned (e.g., .claude/, node_modules/).

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

OUTFILE="STATUS.md"
STALE_DAYS=14
NOW=$(date +%s)

# Collect frontmatter from non-template, non-scaffold markdown files
parse_frontmatter() {
  local file="$1"
  # Extract type, status, owner, last-reviewed from YAML frontmatter
  local in_fm=false
  local type="" status="" owner="" reviewed=""
  while IFS= read -r line; do
    if [[ "$line" == "---" ]]; then
      if $in_fm; then break; fi
      in_fm=true
      continue
    fi
    $in_fm || continue
    case "$line" in
      type:*)     type="${line#type: }" ;;
      status:*)   status="${line#status: }" ;;
      owner:*)    owner="${line#owner: }" ;;
      last-reviewed:*) reviewed="${line#last-reviewed: }" ;;
    esac
  done < "$file"
  # Skip files without frontmatter or with placeholder dates
  [[ -z "$type" || -z "$status" ]] && return
  [[ "$reviewed" == "YYYY-MM-DD" ]] && reviewed=""
  echo "${status}|${type}|${owner}|${reviewed}|${file}"
}

# Parse all qualifying .md files
drafts=()
in_review=()
approved=()
superseded=()

while IFS= read -r f; do
  result=$(parse_frontmatter "$f") || true
  [[ -z "$result" ]] && continue
  IFS='|' read -r s_status s_type s_owner s_reviewed s_path <<< "$result"
  case "$s_status" in
    draft)      drafts+=("$result") ;;
    in-review)  in_review+=("$result") ;;
    approved)   approved+=("$result") ;;
    superseded) superseded+=("$result") ;;
  esac
done < <(
  find . -name '*.md' -not -path './.claude/*' -not -path './references/*' \
    -not -path './output/*' -not -path './node_modules/*' \
    -not -path './examples/test-fixtures/*' \
    -not -name '*_TEMPLATE*' \
    -not -path '*/_TEMPLATE/*' \
  | sort
)

# Check staleness
is_stale() {
  local reviewed="$1"
  [[ -z "$reviewed" ]] && echo "yes" && return
  local rev_ts
  rev_ts=$(date -j -f "%Y-%m-%d" "$reviewed" +%s 2>/dev/null || echo 0)
  local age_days=$(( (NOW - rev_ts) / 86400 ))
  [[ $age_days -gt $STALE_DAYS ]] && echo "yes" || echo "no"
}

# Write STATUS.md
{
  echo "# Status"
  echo ""
  echo "> Auto-generated by \`scripts/status.sh\`. Do not edit manually."
  echo "> Last run: $(date '+%Y-%m-%d %H:%M')"
  echo ""

  # In Review
  echo "## In Review"
  if [[ ${#in_review[@]} -eq 0 ]]; then
    echo "No documents in review."
  else
    echo "| Document | Type | Owner | Last Reviewed | Stale? |"
    echo "|----------|------|-------|---------------|--------|"
    for entry in "${in_review[@]}"; do
      IFS='|' read -r _ s_type s_owner s_reviewed s_path <<< "$entry"
      stale=$(is_stale "$s_reviewed")
      stale_flag=$([[ "$stale" == "yes" ]] && echo "**YES**" || echo "no")
      echo "| ${s_path} | ${s_type} | ${s_owner} | ${s_reviewed:-never} | ${stale_flag} |"
    done
  fi
  echo ""

  # Draft
  echo "## Draft"
  if [[ ${#drafts[@]} -eq 0 ]]; then
    echo "No documents in draft."
  else
    echo "| Document | Type | Owner |"
    echo "|----------|------|-------|"
    for entry in "${drafts[@]}"; do
      IFS='|' read -r _ s_type s_owner s_reviewed s_path <<< "$entry"
      echo "| ${s_path} | ${s_type} | ${s_owner} |"
    done
  fi
  echo ""

  # Approved
  echo "## Approved"
  if [[ ${#approved[@]} -eq 0 ]]; then
    echo "No approved documents."
  else
    echo "| Document | Type | Owner | Last Reviewed |"
    echo "|----------|------|-------|---------------|"
    for entry in "${approved[@]}"; do
      IFS='|' read -r _ s_type s_owner s_reviewed s_path <<< "$entry"
      echo "| ${s_path} | ${s_type} | ${s_owner} | ${s_reviewed:-never} |"
    done
  fi
  echo ""

  # Summary
  total=$(( ${#drafts[@]} + ${#in_review[@]} + ${#approved[@]} + ${#superseded[@]} ))
  echo "## Summary"
  echo "| Status | Count |"
  echo "|--------|-------|"
  echo "| Draft | ${#drafts[@]} |"
  echo "| In Review | ${#in_review[@]} |"
  echo "| Approved | ${#approved[@]} |"
  echo "| Superseded | ${#superseded[@]} |"
  echo "| **Total** | **${total}** |"

} > "$OUTFILE"

echo "Generated ${OUTFILE} — ${total:-0} documents found."
